// TODO: Create a function that returns a license badge based on which license is passed in
// i created an array with all the license descriptions/writings. some of the licenses will take several parts of the array to make the incertion of the year and also the user's
//full name into the template literal easier
var allLi = [
  "MIT License Copyright (c)", "Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the 'Software'), to deal in the Software without restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so, subject to the following conditions: The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software. THE SOFTWARE IS PROVIDED 'AS IS', WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.",
  "BSD 2-Clause License Copyright (c)", "All rights reserved. Redistribution and use in source and binary forms, with or without modification, are permitted provided that the following conditions are met: Redistributions of source code must retain the above copyright notice, this list of conditions and the following disclaimer. Redistributions in binary form must reproduce the above copyright notice, this list of conditions and the following disclaimer in the documentation and/or other materials provided with the distribution. THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS 'AS IS' AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.",
  "BSD 3-Clause License Copyright (c)", "All rights reserved. Redistribution and use in source and binary forms, with or without modification, are permitted provided that the following conditions are met: Redistributions of source code must retain the above copyright notice, this list of conditions and the following disclaimer. Redistributions in binary form must reproduce the above copyright notice, this list of conditions and the following disclaimer in the documentation and/or other materials provided with the distribution. Neither the name of the copyright holder nor the names of its contributors may be used to endorse or promote products derived from this software without specific prior written permission. THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS 'AS IS' AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.",
  "Boost Software License - Version 1.0 - August 17th, 2003 Permission is hereby granted, free of charge, to any person or organization obtaining a copy of the software and accompanying documentation covered by this license (the 'Software') to use, reproduce, display, distribute, execute, and transmit the Software, and to prepare derivative works of the Software, and to permit third-parties to whom the Software is furnished to do so, all subject to the following: The copyright notices in the Software and this entire statement, including the above license grant, this restriction and the following disclaimer, must be included in all copies of the Software, in whole or in part, and all derivative works of the Software, unless such copies or derivative works are solely in the form of machine-executable object code generated by a source language processor. THE SOFTWARE IS PROVIDED 'AS IS', WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.",
  "This is free and unencumbered software released into the public domain. Anyone is free to copy, modify, publish, use, compile, sell, or distribute this software, either in source code form or as a compiled binary, for any purpose, commercial or non-commercial, and by any means. In jurisdictions that recognize copyright laws, the author or authors of this software dedicate any and all copyright interest in the software to the public domain. We make this dedication for the benefit of the public at large and to the detriment of our heirs and successors. We intend this dedication to be an overt act of relinquishment in perpetuity of all present and future rights to this software under copyright law. THE SOFTWARE IS PROVIDED 'AS IS', WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE. For more information, please refer to https://unlicense.org"
]
// If there is no license, return an empty string
function renderLicenseBadge(license)
{
  if (license == "MIT")
  {
    return `[![PyPi license](https://badgen.net/pypi/license/pip/)](https://pypi.com/project/pip/)`;
  }
  else if (license == "BSD 2-Clause License")
  {
    return `[![License](https://img.shields.io/badge/License-BSD_2--Clause-orange.svg)](https://opensource.org/licenses/BSD-2-Clause)`;
  }
  else if (license == "BSD 3-Clause License")
  {
    return `[![License](https://img.shields.io/badge/License-BSD_3--Clause-blue.svg)](https://opensource.org/licenses/BSD-3-Clause)`;
  }
  else if (license == "Boost Software License")
  {
    return `[![License](https://img.shields.io/badge/License-Boost_1.0-lightblue.svg)](https://www.boost.org/LICENSE_1_0.txt)`;
  }
  else if (license == "The Unlicense")
  {
    return `[![Unlicense](https://img.shields.io/badge/License-Unlicense-blue.svg)](https://unlicense.org/)`;
  }
  else if (license == "None")
  {
    return "";
  }
}

// TODO: Create a function that returns the license link
// If there is no license, return an empty string
function renderLicenseLink(license)
{
  if (license == "None")
  {
    return "";
  }
  else if (license == "MIT")
  {
    return `https://mit-license.org/`
  }
  else if (license == "BSD 2-Clause License")
  {
    return `https://opensource.org/licenses/BSD-2-Clause`
  }
  else if (license == "BSD 3-Clause License")
  {
    return `https://opensource.org/licenses/BSD-3-Clause`
  }
  else if (license == "Boost Software License")
  {
    return `https://www.boost.org/users/license.html`
  }
  else if (license == "The Unlicense")
  {
    return `https://unlicense.org/`
  }
}

// TODO: Create a function that returns the license section of README
// If there is no license, return an empty string
//this function takes two parameters, and those parameters have to be defined in generate markdown to work in here
//the two parameters allow for me to place the user's full name into the license found at the bottom of the readme
function renderLicenseSection(license, username)
{
  if (license == "None")
  {
    return "";
  }
  else if (license == "MIT")
  {
    return `## Liscense
${allLi[0]} 2022 ${username}
${allLi[1]}`;
  }
  else if (license == "BSD 2-Clause License")
  {
    return `## Liscense
${allLi[2]} 2022 ${username}

${allLi[3]}`;
  }
  else if (license == "BSD 3-Clause License")
  {
    return `## Liscense
${allLi[4]} 2022 ${username}

${allLi[5]}`;
  }
  else if (license == "Boost Software License")
  {
    return `## Liscense
${allLi[6]}`;
  }
  else if (license == "The Unlicense")
  {
    return `## Liscense
${allLi[7]}`;
  }
}

function renderDeployedPage(deployment)
{
  if (deployment == "This project does not have a deployed page")
  {
    return ""
  }
  else
  {
    return `[Deployed Page](${deployment})`
  }
}

function renderScreenshots(screenshots, alttext)
{
  if (screenshots == false)
  {
    return ""
  }
  else
  {
    //i may make the readme and then once i copy the created file over into a different repository all i would have to do is change the path of the image to one that is found in the new repository to finish everything off
    return `
![A picture of the deployed application](./assets/README%20example.PNG "${alttext}")
![A gif of the deployed application](./assets/Untitled_%20Apr%2022%2C%202022%203_36%20PM.gif "${alttext}")
    `
  }
}

// TODO: Create a function to generate markdown for README
function generateMarkdown(data)
{
  //i define alttext and username here so that the functions above know that i want the user inputed information, otherwise it would be seen as undefined. in addition i can't do data.fullname in the functions above due to scope
  var alttext = data.alttext;
  var username = data.fullname;
  return `# ${data.name}
${renderLicenseBadge(data.license)}
## Description 
${data.description}
${renderDeployedPage(data.deployment)}
## Table of Contents
* [Description](#description)
* [Instillation](#instillation)
* [Usage](#usage)
* [Contribution](#contribution)
* [Tests](#tests)
* [Questions](#questions)
## Instillation 
${data.instillation}
## Usage 
${data.usage}
${renderScreenshots(data.screenshots, alttext)}
## Contribution
${data.contribution}
## Tests
${data.tests}

${renderLicenseSection(data.license, username)}

${renderLicenseLink(data.license)}

## Questions
If you have any further questions contact me here:
 - Email ${data.email}
 - GitHub [${data.username}](https://github.com/${data.username})
`;
}
//there are red sections above in the template literal above, but that is the right spacing to create a bulleted list item in markdown

//module.exports line below allows me to connect this file to the index.js file
module.exports = generateMarkdown;
